export const JUDGE_DATA = {
  criteria: [
    { id: "static",  name: "Статика",       max: 25, color: "#4ade80" },
    { id: "dynamic", name: "Динамика",       max: 25, color: "#ff6a3d" },
    { id: "tech",    name: "Техника",        max: 20, color: "#5ad1ff" },
    { id: "flow",    name: "Связки и поток", max: 15, color: "#9b8cff" },
    { id: "origin",  name: "Оригинальность", max: 10, color: "#4ade80" },
    { id: "show",    name: "Презентация",    max: 5,  color: "#ff7a96" },
  ],
  tiers: [
    { id: "A", label: "Базовый", pts: 1.0 },
    { id: "B", label: "Средний", pts: 2.0 },
    { id: "C", label: "Сложный", pts: 3.5 },
    { id: "D", label: "Эксперт", pts: 5.0 },
    { id: "E", label: "Элита",   pts: 7.0 },
  ],
  statics: [
    { name: "L-sit / уголок",             tier: "A" },
    { name: "Back lever (задний вис)",    tier: "B" },
    { name: "Human flag (флаг)",          tier: "C" },
    { name: "Front lever (передний вис)", tier: "C" },
    { name: "90° hold (упор углом)",      tier: "D" },
    { name: "Planche (планш)",            tier: "D" },
    { name: "One-arm handstand",          tier: "D" },
    { name: "Maltese (мальтез)",          tier: "E" },
    { name: "Victorian",                  tier: "E" },
  ],
  dynamics: [
    { name: "Muscle-up (выход силой)",   tier: "A" },
    { name: "Explosive pull / 360 pull", tier: "B" },
    { name: "Muscle-up 360",             tier: "C" },
    { name: "Shrimp flip",               tier: "C" },
    { name: "Geinger",                   tier: "D" },
    { name: "Slap muscle-up ×2",         tier: "D" },
    { name: "540 muscle-up",             tier: "D" },
    { name: "Bar flip / backflip",       tier: "E" },
    { name: "Switch blade",              tier: "E" },
  ],
  deductions: [
    { id: "slip",  name: "Срыв с элемента",           pts: 2.0 },
    { id: "fall",  name: "Падение / касание земли",   pts: 3.0 },
    { id: "dirty", name: "Незачтённый элемент",       pts: 1.0 },
    { id: "time",  name: "Нарушение тайминга (за 5с)", pts: 0.5 },
  ],
  ranks: [
    { min: 90, name: "ЭЛИТА",    color: "#4ade80" },
    { min: 75, name: "ПРОФИ",    color: "#5ad1ff" },
    { min: 60, name: "УМЕЛЫЙ",   color: "#9b8cff" },
    { min: 40, name: "ЛЮБИТЕЛЬ", color: "#ff6a3d" },
    { min: 0,  name: "НОВИЧОК",  color: "#888" },
  ],
} as const
